version: "3.8"

services:
    portainer:
        image: portainer/portainer-ce:2.5.1-alpine

        ports:
            - "9900:9000"
        networks:
            - portainer
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == manager]
                
            labels:
                com.docker.swarm.service.name: utils_portainer
                io.kubernetes.container.name: POD
                io.kubernetes.docker.type: container
        
        command: >
            -H unix:///var/run/docker.sock
            --admin-password-file '/run/secrets/portainer-pass'
            --hide-label com.docker.swarm.service.name=utils_portainer

        secrets:
            - portainer-pass

networks:
    portainer:

volumes:
    portainer_data:
        external: true

secrets:
    portainer-pass:
        external: true
